language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "asethi0-github"
    token:
      secure: f95ebe8a60953305f18973c867e44072c4a927ff
jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
